version: '3.8'

services:
  # Service MySQL
  mysqldb:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: stationSki
    ports:
      - "3316:3306"  # Expose MySQL on port 3313
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service de l'application
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: sarra523/gestionski:v1.0
    restart: on-failure
    ports:
      - "8083:8082"  # Expose l'application sur le port 8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    volumes:
      - .m2:/root/.m2  # Monter le cache local Maven
    stdin_open: true
    tty: true

volumes:
  db:
    driver: local  # Définir le volume pour la persistance des données MySQL
